export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Hero } from "./hero/Hero";
export { default as Button } from "./button/Button";
export { default as BreadCrumb } from "./breadcrumb/BreadCrumb";
export { default as SmallLoader } from "./smallLoader/SmallLoader";
export { default as PreLoader } from "./preloader/Preloader";
export { default as QRCodeGenerator } from "./qrCode/QRCode";
export { default as Modal } from "./modal/Modal";
